### ISSUE TITLE
Question regarding KDE Plasma and Qtile together

### ISSUE THREAD

**Issue by webbb82** [jrwrigh/dotfiles2.0#1]
Figured that would get your attention. You replied to a qtile questoin I had and you sent me a link to your config. I was looking at it and noticed you were importing plasma. DOes that mean you got qtile and plasma to play together? Ive been trying to have both installed in my pc without creating a black hole for some time now

**Comment by jrwrigh** [comment]
No need to try and get my attention.

Yes, I have qtile and plasma working together. I've had it that way for about 2 years now (at least) and it's been working fine. Note I'm working off my fork of plasma (which has separate border size controls for the outside of the monitor vs between windows, see https://github.com/numirias/qtile-plasma/pull/22), but that shouldn't affect anything.

**Comment by webbb82** [comment]
so is this kde plasma inside qtile?

**Comment by jrwrigh** [comment]
No, this is not KDE plasma. qtile-plasma is a qtile layout that's similar to how i3 does tiling window management. There's no relation to KDE Plasma.

I do not believe it's possible to run KDE Plasma and qtile simultaneously.

**Comment by webbb82** [comment]
there is a away, I saw a few posts about it but there is a bunch of stuff you have to change like making a new xsession profile so krunner and dmenu/rofi dont fight. I think i saved the post ill see if i can find it.  but also i just came to realize in qtile there really is no way of setting icons or icon packs. then also no real settings menu, all we have is the config file. or am i missing something. Because in arcolinux they have a build in settings they provide but in garuda there is not much at all

**Comment by jrwrigh** [comment]
I should clarify; there's no way to have KDE plasma's window manager and qtile run simultaneously. I forgot that KDE is a full desktop environment, not just a WM. So yes, you can run both that the same time, but only certain components.

Similarly, dmenu/rofi aren't apart of qtile explicitly; qtile is a window manager only. It does have a function for running dmenu things, but it's not necessary to use. All that to say, I'm not sure where the dmenu/rofi vs krunner conflict is coming from unless you've installed and set those up in addition to qtile. 

The way I'd approach it is that you could take a KDE Plasma installation, install qtile from source (see [Qtile documentation](http://docs.qtile.org/en/stable/manual/install/index.html#installing-from-source)), then enable qtile. When I first tried out i3, it was on top of XFCE in a similar configuration that you (I think) want to have (keep all of XFCE's tools, but trade the window manager for qtile) and I think I did it this way (but it's been years since I did that last).

**Comment by webbb82** [comment]
check this out One guy has I3 and plasma together im still looking got the qtile one. and it was kwin that you have to deal with and i think thats where xsessions comes into play https://github.com/avivace/dotfiles

**Comment by jrwrigh** [comment]
Gotcha. You should be able to trade out `/usr/bin/i3` with `/path/to/qtile start` in the xsessions file that the README in that dotfiles repo suggets. May also have to migrate the floating window settings that they have in their i3 config (also detailed in the README).

I'll go ahead and close the issue here, but feel free to ask questions or whatever else.
